export const dummyData = [
  {
    accountId: "1",
    accountName: "Acme Innovations Acc 1",
    balances: [
      {
        assetId: "1",
        assetName: "Bitcoin",
        assetSymbol: "BTC",
        totalBalance: 847.38,
        availableBalance: 612.05,
      },
      {
        assetId: "2",
        assetName: "Solana",
        assetSymbol: "SOL",
        totalBalance: 391.71,
        availableBalance: 310.43,
      },
      {
        assetId: "3",
        assetName: "Ethereum",
        assetSymbol: "ETH",
        totalBalance: 574.09,
        availableBalance: 430.67,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 763.55,
        availableBalance: 763.55,
      },
    ],
  },
  {
    accountId: "2",
    accountName: "Acme Innovations Acc 2",
    balances: [
      {
        assetId: "1",
        assetName: "Bitcoin",
        assetSymbol: "BTC",
        totalBalance: 215.80,
        availableBalance: 178.26,
      },
      {
        assetId: "3",
        assetName: "Ethereum",
        assetSymbol: "ETH",
        totalBalance: 682.44,
        availableBalance: 540.78,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 437.12,
        availableBalance: 437.12,
      },
    ],
  },
  {
    accountId: "3",
    accountName: "Acme Innovations Acc 3",
    balances: [
      {
        assetId: "2",
        assetName: "Solana",
        assetSymbol: "SOL",
        totalBalance: 906.25,
        availableBalance: 724.88,
      },
      {
        assetId: "3",
        assetName: "Ethereum",
        assetSymbol: "ETH",
        totalBalance: 358.61,
        availableBalance: 290.34,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 193.74,
        availableBalance: 193.74,
      },
    ],
  },
  {
    accountId: "4",
    accountName: "Acme Innovations Acc 4",
    balances: [
      {
        assetId: "1",
        assetName: "Bitcoin",
        assetSymbol: "BTC",
        totalBalance: 471.53,
        availableBalance: 385.02,
      },
      {
        assetId: "2",
        assetName: "Solana",
        assetSymbol: "SOL",
        totalBalance: 128.95,
        availableBalance: 97.60,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 854.33,
        availableBalance: 854.33,
      },
    ],
  },
  {
    accountId: "5",
    accountName: "Acme Innovations Acc 5",
    balances: [
      {
        assetId: "1",
        assetName: "Bitcoin",
        assetSymbol: "BTC",
        totalBalance: 739.16,
        availableBalance: 601.50,
      },
      {
        assetId: "2",
        assetName: "Solana",
        assetSymbol: "SOL",
        totalBalance: 462.83,
        availableBalance: 415.28,
      },
      {
        assetId: "3",
        assetName: "Ethereum",
        assetSymbol: "ETH",
        totalBalance: 187.41,
        availableBalance: 142.94,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 593.67,
        availableBalance: 593.67,
      },
    ],
  },
];
