export const dummyData = [
  {
    accountId: "1",
    accountName: "Acme Innovations Acc 1",
    balances: [
      {
        assetId: "1",
        assetName: "Bitcoin",
        assetSymbol: "BTC",
        totalBalance: 10000,
        availableBalance: 8000,
      },
      {
        assetId: "2",
        assetName: "Solana",
        assetSymbol: "SOL",
        totalBalance: 3200,
        availableBalance: 3000,
      },
      {
        assetId: "3",
        assetName: "Ethereum",
        assetSymbol: "ETH",
        totalBalance: 5000,
        availableBalance: 4000,
      },
      {
        assetId: "4",
        assetName: "United States Dollar",
        assetSymbol: "USD",
        totalBalance: 15000,
        availableBalance: 12000,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 8500,
        availableBalance: 8500,
      },
    ],
  },
  {
    accountId: "2",
    accountName: "Acme Innovations Acc 2",
    balances: [
      {
        assetId: "1",
        assetName: "Bitcoin",
        assetSymbol: "BTC",
        totalBalance: 2500,
        availableBalance: 2000,
      },
      {
        assetId: "3",
        assetName: "Ethereum",
        assetSymbol: "ETH",
        totalBalance: 7800,
        availableBalance: 6500,
      },
      {
        assetId: "4",
        assetName: "United States Dollar",
        assetSymbol: "USD",
        totalBalance: 20000,
        availableBalance: 18000,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 5000,
        availableBalance: 5000,
      },
    ],
  },
  {
    accountId: "3",
    accountName: "Acme Innovations Acc 3",
    balances: [
      {
        assetId: "2",
        assetName: "Solana",
        assetSymbol: "SOL",
        totalBalance: 9000,
        availableBalance: 8000,
      },
      {
        assetId: "3",
        assetName: "Ethereum",
        assetSymbol: "ETH",
        totalBalance: 3300,
        availableBalance: 3000,
      },
      {
        assetId: "4",
        assetName: "United States Dollar",
        assetSymbol: "USD",
        totalBalance: 11000,
        availableBalance: 9500,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 2200,
        availableBalance: 2200,
      },
    ],
  },
  {
    accountId: "4",
    accountName: "Acme Innovations Acc 4",
    balances: [
      {
        assetId: "1",
        assetName: "Bitcoin",
        assetSymbol: "BTC",
        totalBalance: 500,
        availableBalance: 400,
      },
      {
        assetId: "2",
        assetName: "Solana",
        assetSymbol: "SOL",
        totalBalance: 1500,
        availableBalance: 1200,
      },
      {
        assetId: "4",
        assetName: "United States Dollar",
        assetSymbol: "USD",
        totalBalance: 30000,
        availableBalance: 28000,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 12000,
        availableBalance: 12000,
      },
    ],
  },
  {
    accountId: "5",
    accountName: "Acme Innovations Acc 5",
    balances: [
      {
        assetId: "1",
        assetName: "Bitcoin",
        assetSymbol: "BTC",
        totalBalance: 7200,
        availableBalance: 7000,
      },
      {
        assetId: "2",
        assetName: "Solana",
        assetSymbol: "SOL",
        totalBalance: 4400,
        availableBalance: 4000,
      },
      {
        assetId: "3",
        assetName: "Ethereum",
        assetSymbol: "ETH",
        totalBalance: 1800,
        availableBalance: 1500,
      },
      {
        assetId: "5",
        assetName: "Tether",
        assetSymbol: "USDT",
        totalBalance: 6600,
        availableBalance: 6600,
      },
    ],
  },
];
